### ISSUE TITLE
import project to IDEA, error happened

### ISSUE THREAD

**Issue by hanyou** [shendepu/moqui-react-ssr#1]
Error:(7, 0) Could not find method parseComponent() for arguments [root project 'moqui-react-ssr'] on root project 'moqui-react-ssr' of type org.gradle.api.Project.
<a href="openFile:/Users/hanyou/IdeaProjects/moqui-react-ssr/build.gradle">Open File</a>

**Comment by shendepu** [comment]
Where did you run command? Did you run it at the framework root path? It seems that you run it at the `moqui-react-ssr` folder. but it should be run moqui-framework folder 

This addon is just component of [moqui-framework](https://github.com/moqui/moqui-framework), and is a glue to pull moqui and nashorn together. 

If you are only interested in SSR with Nashorn, the most code is in `React` and `ReactRender` class
